restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    DishListView,
    CookCreateView,
    CookListView,
    CookDetailView,
    DishDetailView,
    IngredientListView,
    DishTypesListView,
    DishUpdateView,
    DishDeleteView,
    CookDeleteView,
    CookUpdateView,
    DishCreateView,
    toggle_assign_to_dish,
    IngredientCreateView,
    DishTypesCreateView,
    IngredientDeleteView,
    DishTypesDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "registration/",
        CookCreateView.as_view(),
        name="registration"
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list"
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create"
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete"
    ),
    path(
        "dish_types/",
        DishTypesListView.as_view(),
        name="dish-types-list"
    ),
    path(
        "dish_types/create/",
        DishTypesCreateView.as_view(),
        name="dish-types-create"
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypesDeleteView.as_view(),
        name="dish-types-delete"
    ),

]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/header.html
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-gradient-dark z-index-3 py-3">
      <div class="container-fluid">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link{% if request.resolver_match.url_name == 'index' %} active{% endif %}"
              href="{% url 'restaurant:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if request.resolver_match.url_name == 'dish-list' %} active{% endif %}"
              href="{% url 'restaurant:dish-list' %}">Dishes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if request.resolver_match.url_name == 'cook-list' %} active{% endif %}"
              href="{% url 'restaurant:cook-list' %}">Cooks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if request.resolver_match.url_name == 'ingredient-list' %} active{% endif %}"
              href="{% url 'restaurant:ingredient-list' %}">Ingredients</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if request.resolver_match.url_name == 'dish-types-list' %} active{% endif %}"
              href="{% url 'restaurant:dish-types-list' %}">DishTypes</a>
            </li>
              </ul>
          <ul class="navbar-nav mb-2 mb-lg-0">
            {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link{% if request.resolver_match.url_name == 'cook-detail' %} active{% endif %}"
                  href="{% url 'restaurant:cook-detail' pk=user.id %}">User: {{ user.get_username }}</a></li>
                <li class="nav-item">
                  <a class="nav-link"
                  href="{% url 'logout' %}">Logout</a></li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'login' %} active{% endif %}"
                href="{% url 'login'%}?next={% url 'restaurant:index' %}">Login</a></li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'registration' %} active{% endif %}"
                href="{% url 'restaurant:registration'%}?next={% url 'restaurant:index' %}">Registration</a></li>

            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

templates/includes/pagination.html
{% if is_paginated %}
{% load query_transform %}
  <ul class="pagination pagination-primary m-4">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
        <a class="page-link">{{ page_obj.number }}</a>
      </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
    <p class="pagination-info">{{ page_obj.number }} of {{ paginator.num_pages }}</p>
  </ul>
{% endif %}