restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    DishListView,
    CookCreateView,
    CookListView,
    CookDetailView,
    DishDetailView,
    IngredientListView,
    DishTypesListView,
    DishUpdateView,
    DishDeleteView,
    CookDeleteView,
    CookUpdateView,
    DishCreateView,
    toggle_assign_to_dish,
    IngredientCreateView,
    DishTypesCreateView,
    IngredientDeleteView,
    DishTypesDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "registration/",
        CookCreateView.as_view(),
        name="registration"
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list"
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create"
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete"
    ),
    path(
        "dish_types/",
        DishTypesListView.as_view(),
        name="dish-types-list"
    ),
    path(
        "dish_types/create/",
        DishTypesCreateView.as_view(),
        name="dish-types-create"
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypesDeleteView.as_view(),
        name="dish-types-delete"
    ),

]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class DishTypes(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", kwargs={"pk": self.pk})


class Ingredient(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    dish_type = models.ForeignKey(DishTypes, on_delete=models.CASCADE, related_name="dishes")
    ingredients = models.ManyToManyField(Ingredient, related_name="dishes")
    cooks = models.ManyToManyField(Cook, related_name="dishes", blank=True)

    def __str__(self):
        return self.name

restaurant/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from restaurant.models import Cook, Dish, Ingredient


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "username",
            "years_of_experience",
            "first_name",
            "last_name",
        )


class SearchForm(forms.Form):
    search = forms.CharField(max_length=255, required=False)


class DishForm(forms.ModelForm):

    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.SelectMultiple,
    )

    class Meta:
        model = Dish
        fields = (
            "name",
            "description",
            "price",
            "dish_type",
            "ingredients"
        )


class CookForm(forms.ModelForm):

    class Meta:
        model = Cook
        fields = (
            "username",
            "years_of_experience",
            "first_name",
            "last_name",
        )

restaurant/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from restaurant.forms import SearchForm, CookCreationForm, DishForm, CookForm
from restaurant.models import DishTypes, Dish, Ingredient, Cook


def index(request):

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishTypes.objects.count()

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
    }

    return render(request, "restaurant/index.html", context=context)


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    context_object_name = "dish_list"
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        search = self.request.GET.get("search", "")
        context["search_form"] = SearchForm(initial={"search": search})
        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["search"]
            )
        return queryset


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm

    def get_success_url(self):
        dish_id = self.object.id
        success_url = reverse("restaurant:dish-detail", args=[dish_id])
        return success_url


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dish-list")


class CookCreateView(generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy('restaurant:index')

    def form_valid(self, form):
        self.object = form.save()
        cook = authenticate(
            username=self.object.username,
            password=form.cleaned_data['password1']
        )
        login(self.request, cook)
        return redirect(self.get_success_url())


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    context_object_name = "cook_list"
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        search = self.request.GET.get("search", "")
        context["search_form"] = SearchForm(initial={"search": search})
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["search"]
            )
        return queryset


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookForm

    def get_success_url(self):
        cook_id = self.object.id
        success_url = reverse("restaurant:cook-detail", args=[cook_id])
        return success_url

    def form_valid(self, form):
        self.object.dishes.set(form.cleaned_data['dishes'])
        return super().form_valid(form)


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:index")


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    context_object_name = "ingredient_list"
    paginate_by = 18


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("restaurant:ingredient-list")


class DishTypesListView(LoginRequiredMixin, generic.ListView):
    model = DishTypes
    context_object_name = "dish_types_list"
    template_name = "restaurant/dish_types_list.html"
    paginate_by = 18


class DishTypesCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishTypes
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-types-list")
    template_name = "restaurant/dish_types_form.html"


class DishTypesDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishTypes
    success_url = reverse_lazy("restaurant:dish-types-list")


@login_required
def toggle_assign_to_dish(request, pk):
    cooker = Cook.objects.get(id=request.user.id)
    if (
        Dish.objects.get(id=pk) in cooker.dishes.all()
    ):
        cooker.dishes.remove(pk)
    else:
        cooker.dishes.add(pk)

    next_url = request.GET.get('next', '/')
    print(request.GET)
    return redirect(next_url)

templates/restaurant/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete yourself?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'restaurant:cook-detail' pk=cook.id %}" class="btn btn-secondary">No</a>

  </form>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ cook.username }}
    {% if user.id == cook.id %}
      <a href="{% url 'restaurant:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
        Update
      </a>
      <a href="{% url 'restaurant:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>
    {% endif %}
  </h1>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>


  <h4 class="section-title">Dishes</h4>

  <div class="row">
    {% for dish in cook.dishes.all %}
      <div class="col-2">
        <div class="card custom-card">
          <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">
            <div class="card-header">{{ dish.name }}</div>
          </a>
          <div class="card-body">
            <h5 class="card-title">{{ dish.price}}</h5>
          </div>
          <a href="{% url 'restaurant:toggle-dish-assign' pk=dish.id %}?next={{ request.get_full_path }}"
            class="btn btn-danger link-to-page unsubscribe-btn">
            Unsubscribe
          </a>
        </div>
      </div>
    {% empty %}
      <p class="no-dishes-msg">No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/restaurant/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <form action="" method="post" novalidate  class="create-form">
    <h1>{{ object|yesno:"Update,Create" }} cook</h1>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <input type="hidden" name="next" value="{{ next }}" />

  </form>
{% endblock %}

templates/restaurant/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Cooks List
  </h1>
  <form action="" method="get" class="search-form">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-primary">
  </form>

  <div class="row">
    {% if cook_list %}
      {% for cook in cook_list %}
        <div class="col-md-4">
          <a href="{{ cook.get_absolute_url }}">
            <div class="card mb-3">
              <div class="card-body cook-card">
                <h5 class="card-title">{{ cook.username }}</h5>
                <h6 class="card-subtitle mb-2"> Years of experience: {{ cook.years_of_experience }}</h6>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    {% else %}
      <p>There are no cooks in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'restaurant:dish-detail' pk=dish.id %}" class="btn btn-secondary">No</a>

  </form>
{% endblock %}

templates/restaurant/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish.name }}
    <a href="{% url 'restaurant:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
    <a href="{% url 'restaurant:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
  </h1>

  <h2>
    Price: {{ dish.price }}
  </h2>
  <h3>
    Type: {{ dish.dish_type }}
  </h3>
  <p>Description: {{ dish.description }}</p>

  <ul>
    Ingredients
    {% for ingredient in dish.ingredients.all %}
      <li>{{ ingredient.name }}</li>
    {% endfor %}
  </ul>
  <hr>
    {% if dish in user.dishes.all %}
      <a href="{% url 'restaurant:toggle-dish-assign' pk=dish.id %}?next={{ request.get_full_path }}" class="btn btn-success link-to-page">
        I can cook this
      </a>
    {% else %}
      <a href="{% url 'restaurant:toggle-dish-assign' pk=dish.id %}?next={{ request.get_full_path }}" class="btn btn-danger link-to-page">
        I can`t cook this
      </a>
    {% endif %}
  <hr>
  <div>
    Cooks:
    {% for cook in dish.cooks.all %}
      <a href="{% url 'restaurant:cook-detail' pk=cook.id %}" class="btn btn-secondary link-to-page">
        {{ cook.username }}
      </a>
    {% endfor %}
    {% if not dish.cooks.all %}
      <p>Nobody can cook this</p>
    {% endif %}

  </div>


{% endblock %}

templates/restaurant/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <form action="" method="post" novalidate class="create-form">
    <h1>{{ object|yesno:"Update,Create" }} dish</h1>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dishes List
    <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form action="" method="get" class="search-form">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-primary">
  </form>

  <div class="row">
    {% if dish_list %}
      {% for dish in dish_list %}
        <div class="col-md-4">
          <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">
            <div class="card mb-3">
              <div class="card-body">
                <div>
                <h5 class="card-title">{{ dish.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ dish.dish_type }}</h6>
                  {% if dish in user.dishes.all %}
                    <a href="{% url 'restaurant:toggle-dish-assign' pk=dish.id %}?next={{ request.get_full_path }}" class="btn btn-success link-to-page">
                      I can cook this
                    </a>
                  {% else %}
                    <a href="{% url 'restaurant:toggle-dish-assign' pk=dish.id %}?next={{ request.get_full_path }}" class="btn btn-danger link-to-page">
                      I can`t cook this
                    </a>
                  {% endif %}
                </div>
                <p class="card-text">{{ dish.description }}</p>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    {% else %}
      <p>There are no dishes in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/restaurant/dish_types_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <form action="" method="post" novalidate  class="create-form">
    <h1>{{ object|yesno:"Update,Create" }} type</h1>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/dish_types_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish types
    <a href="{% url 'restaurant:dish-types-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>


  <div class="row">
    {% if dish_types_list %}
      {% for dish_type in dish_types_list %}
        <div class="col-md-2">

            <div class="card mb-3 align-items-center">
              <div class="card-body">
                <h5 class="card-title mini-card-title">{{ dish_type.name }}</h5>
              </div>
              <a href="{% url 'restaurant:dish-types-delete' pk=dish_type.id %}" class="btn btn-danger link-to-page delete">
                Delete
              </a>
            </div>
        </div>
      {% endfor %}
    {% else %}
      <p>There are no dish types in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <header class="header-2">
      <div class="page-header min-vh-75 relative" style="background-image: url('/static/img/img.png')">
        <div class="container">
          <div class="row">
            <div class="col-lg-7 text-center mx-auto">
              <h1 class="text-white pt-3 mt-n5">Restaurant kitchen service</h1>
              <p class="lead text-white mt-3">My first django project<br>There should be some text here</p>
            </div>
          </div>
        </div>

        <div class="position-absolute w-100 z-index-1 bottom-0">
          <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
            <defs>
              <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
            </defs>
            <g class="moving-waves">
              <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"></use>
              <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"></use>
              <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"></use>
              <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"></use>
              <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"></use>
              <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"></use>
            </g>
          </svg>
        </div>
      </div>
    </header>

    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state1">{{num_dishes}}</span></h1>
                  <h5 class="mt-3">Dishes</h5>
                  <p class="text-sm">From buttons, to inputs, navbars, alerts or cards, you are covered</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state2">{{num_cooks}}</span></h1>
                  <h5 class="mt-3">Cooks</h5>
                  <p class="text-sm">Mix the sections, change the colors and unleash your creativity</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state3" >{{num_dish_types}}</h1>
                  <h5 class="mt-3">Dish types</h5>
                  <p class="text-sm">Save 3-4 weeks of work when you use our pre-made pages for your website</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/restaurant/ingredient_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete ingredient: {{ ingredient.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'restaurant:ingredient-list' %}" class="btn btn-secondary">No</a>

  </form>
{% endblock %}

templates/restaurant/ingredient_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <form action="" method="post" novalidate  class="create-form">
    <h1>{{ object|yesno:"Update,Create" }} ingredient</h1>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/ingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Ingredients List
    <a href="{% url 'restaurant:ingredient-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>


  <div class="row">
    {% if ingredient_list %}
      {% for ingredient in ingredient_list %}
        <div class="col-md-2">

          <div class="card mb-3 mini-card align-items-center">
            <a href="{% url 'restaurant:index' %}">
              <div class="card-body">
                <h5 class="card-title mini-card-title">{{ ingredient.name }}</h5>
              </div>
            </a>
          <a href="{% url 'restaurant:ingredient-delete' pk=ingredient.id %}" class="btn btn-danger delete">
            Delete
          </a>
          </div>

        </div>
      {% endfor %}
    {% else %}
      <p>There are no ingredients in the service.</p>
    {% endif %}
  </div>
{% endblock %}